fabricApi {
    configureDataGeneration() {
        client = true
        modId  = project.mod_id
    }
}

addSubmodules(project, [ 'core-api', 'gui-api' ])

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    implementation "org.snakeyaml:snakeyaml-engine:2.9"
    modCompileOnly "com.terraformersmc:modmenu:${project.mod_menu_version}"
}
