plugins {
    id "java-library"
    id "maven-publish"
    id "fabric-loom" version "${loom_version}" apply false
    id "com.github.gmazzo.buildconfig" version '5.5.1' apply false
    id "me.modmuss50.remotesign" version "0.5.0" apply false
	id "me.modmuss50.mod-publish-plugin" version "0.4.5"
}

import groovy.json.JsonSlurper

def nonPublish = [
    "test-mod"
]

def addSubmodules(project, List<String> dependencies)
{
    def deps = dependencies.iterator().collect {
        project.dependencies.project(path: ":$it", configuration: 'namedElements')
    }

	def clientOutputs = dependencies.iterator().collect {
        findProject(":$it").sourceSets.client.output
    }

	project.dependencies {
		deps.each {
			api it
		}

		clientOutputs.each {
			clientImplementation it
		}
	}

	def depNodes = deps.collect {
		[
			groupId: it.group,
			artifactId: it.name,
			version: it.version,
			scope: "compile"
		]
	}

	project.publishing {
		publications {
			mavenJava(MavenPublication) {
				pom.withXml {
					def depsNode = asNode().appendNode("dependencies")

					for (def depNode in depNodes) {
						def node = depsNode.appendNode("dependency")

						for (def entry in depNode) {
							node.appendNode(entry.key, entry.value)
						}
					}
				}
			}
		}
	}
}

static def getPom(Project project, MavenPom pom) {
	def mod_file = project.file("src/main/resources/fabric.mod.json")

	if (!mod_file.exists())
		mod_file = project.file("src/client/resources/fabric.mod.json")

    def metadata = new JsonSlurper().parse(mod_file)

    pom.name        = metadata.name
    pom.url         = "https://lumialights.xyz/Novia"
    pom.description = metadata.description

    pom.licenses {
        license {
            name = "MIT"
            url  = "https://mit-license.org/"
        }
    }

    pom.developers {
        developer {
            name = "LumiaLights"
            url  = "https://lumialights.xyz"
        }
    }

    pom.scm {
        connection          = "scm:git:git://github.com/LumiaLights/Novia.git"
        developerConnection = "scm:git:git@github.com:LumiaLights/Novia.git"
        url                 = "https://lumialights.xyz/Novia"
    }
}

allprojects {
    group   = project.root_group
    version = project.mod_version

    apply plugin: "maven-publish"
    apply plugin: "me.modmuss50.remotesign"

    tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }

    remoteSign {
        requestUrl = providers.environmentVariable("SIGNING_SERVER")
		pgpAuthKey = providers.environmentVariable("SIGNING_PGP_KEY")
		jarAuthKey = providers.environmentVariable("SIGNING_JAR_KEY")

        useDummyForTesting = !providers.environmentVariable("SIGNING_SERVER").present

		afterEvaluate {
			sign publishing.publications.mavenJava
		}
    }

    publishing {
        repositories.mavenLocal()
    }

    apply plugin: "java-library"
    apply plugin: "fabric-loom"
    apply plugin: "com.github.gmazzo.buildconfig"

    tasks.withType(JavaCompile).configureEach {
        it.options.release = project.java_version as Integer
    }

    java { withSourcesJar() }
    loom {
        splitEnvironmentSourceSets()

        mixin {
			useLegacyMixinAp = false
		}
    }

    allprojects.each {p ->
        loom.mods.register(p.name) {
            sourceSet p.sourceSets.main
            sourceSet p.sourceSets.client
        }
    }

    repositories {
        maven {
            name = 'DJTheRedstoner'
            url  = 'https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1'
        }
    }

    dependencies {
        minecraft          "com.mojang:minecraft:${project.minecraft_version}"
        mappings           "net.fabricmc:yarn:${project.yarn_mappings}:v2"
        modImplementation  "net.fabricmc:fabric-loader:${project.loader_version}"
        modImplementation  "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
        testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
        modRuntimeOnly     "me.djtheredstoner:DevAuth-fabric:${project.mod_auth_version}"
    }

    test { useJUnitPlatform() }

    tasks.withType(ProcessResources).configureEach {
        inputs.property "version",           project.version
        inputs.property "mod_id",            project.mod_id
        inputs.property "mod_name",          project.mod_name
        inputs.property "minecraft_version", project.minecraft_version
        inputs.property "loader_version",    project.loader_version
        inputs.property "java_version",      project.java_version

        filteringCharset "UTF-8"

        filesMatching("fabric.mod.json") {
            expand "version":           inputs.properties.version,
                   "mod_id":            inputs.properties.mod_id,
                   "mod_name":          inputs.properties.mod_name,
                   "minecraft_version": inputs.properties.minecraft_version,
                   "loader_version":    inputs.properties.loader_version,
                   "java_version":      inputs.properties.java_version
        }
    }

    remoteSign {
        sign remapJar
    }

    tasks.register('generateResources') {
        group = "novia"
    }

    if (it.name == "novia")
        return

    def define_package = (project.name != "novia" ? ("${group}.api." + project.name.split("-")[0]) : group)

    buildConfig {
        className("ApiDefine")
        packageName(String.valueOf(define_package))

        buildConfigField(String, "API_ID",      project.mod_id)
        buildConfigField(String, "API_NAME",    project.mod_name)
        buildConfigField(String, "API_VERSION", project.version)
    }
}

subprojects {
    base {
        archivesName = project.name
    }

    if (nonPublish.contains(project.name))
    {
        return
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    getPom(project, pom)
                }

                artifact(signRemapJar.output) {
                    builtBy(signRemapJar)
                }

                artifact(remapSourcesJar) {
                    builtBy(remapSourcesJar)
                }
            }
        }
    }

    loom.disableDeprecatedPomGeneration(publishing.publications.mavenJava)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                getPom(rootProject, pom)
            }

            artifact(signRemapJar.output) {
                builtBy(signRemapJar)
            }

            artifact(remapSourcesJar) {
                builtBy(remapSourcesJar)
            }

            List<Map<String, String>> dependencies = []

            subprojects.each {
                dependencies.add([
                    'groupId': it.group,
					'artifactId': it.name,
					'version': it.mod_version,
					'scope': 'compile'
                ])
            }

			pom.withXml {
				def depsNode = asNode().appendNode("dependencies")

				for (dep in dependencies)
                {
					def depNode = depsNode.appendNode("dependency")
					depNode.appendNode("groupId", dep['groupId'])
					depNode.appendNode("artifactId", dep['artifactId'])
					depNode.appendNode("version", dep['version'])
					depNode.appendNode("scope", dep['scope'])
				}
			}
        }
    }
}

loom.disableDeprecatedPomGeneration(publishing.publications.mavenJava)

dependencies {
    afterEvaluate {
        subprojects.each {
            api                  project(path: "${it.path}", configuration: "namedElements")
            clientImplementation project("${it.path}").sourceSets.client.output
        }
    }
}

subprojects.each {
    remapJar.dependsOn("${it.path}:remapJar")
}

configurations {
	nestedJars {
		transitive = false
	}
}

dependencies {
    subprojects.each {
        nestedJars project("${it.path}")
    }
}

remapJar {
    nestedJars.from configurations.nestedJars
}

assemble.dependsOn signRemapJar
