org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

fabric.loom.multiProjectOptimisation=true

minecraft_version = 1.21.8
yarn_mappings     = 1.21.8+build.1
loader_version    = 0.17.2
fabric_version    = 0.132.0+1.21.8
java_version      = 21
mod_menu_version  = 15.0.0-beta.3
loom_version      = 1.11-SNAPSHOT
mod_auth_version  = 1.2.1

root_group = xyz.lumialights.novia

mod_version = 1.0.0
mod_id      = novia
mod_name    = Novia
